from src.utils.regexes.common import FILENAME_SPECIAL_CHARS_PATTERN
from src.utils.regexes.proxy import (
    PROXY_PROTOCOL_IP_PORT_PATTERN,
    PROXY_PROTOCOL_IP_PORT_USER_PASS_PATTERN,
    PROXY_PROTOCOL_PATTERN,
    PROXY_PROTOCOL_USER_PASS_IP_PORT_PATTERN,
)
from src.utils.regexes.roblox import (
    ROBLOX_AGE_GROUP_PATTERN,
    ROBLOX_COOKIE_PATTERN,
    ROBLOX_COOKIE_PATTERN_BYTES,
    ROBLOX_VERSION_PATH_PATTERN,
    STRING_100_PLUS_SYMBOLS_PATTERN,
    STRING_100_PLUS_SYMBOLS_PATTERN_BYTES,
)
from src.utils.regexes.ui import (
    CUBIC_BEZIER_PATTERN,
    NORMALIZE_QT_KEY_PATTERN,
    QSS_TARGET_PATTERN,
    QSS_TARGET_PROPERTY_PATTERN,
    SIGNAL_NAME_PATTERN,
)

__all__ = [
    'FILENAME_SPECIAL_CHARS_PATTERN',
    'PROXY_PROTOCOL_IP_PORT_PATTERN',
    'PROXY_PROTOCOL_IP_PORT_USER_PASS_PATTERN',
    'PROXY_PROTOCOL_PATTERN',
    'PROXY_PROTOCOL_USER_PASS_IP_PORT_PATTERN',
    'ROBLOX_AGE_GROUP_PATTERN',
    'ROBLOX_COOKIE_PATTERN',
    'ROBLOX_COOKIE_PATTERN_BYTES',
    'ROBLOX_VERSION_PATH_PATTERN',
    'STRING_100_PLUS_SYMBOLS_PATTERN',
    'STRING_100_PLUS_SYMBOLS_PATTERN_BYTES',
    'CUBIC_BEZIER_PATTERN',
    'NORMALIZE_QT_KEY_PATTERN',
    'QSS_TARGET_PATTERN',
    'QSS_TARGET_PROPERTY_PATTERN',
    'SIGNAL_NAME_PATTERN',
]
