CONFIG_COMMENT_SYMBOLS = ('!', '#')
CONFIG_INDENT = ' ' * 2
CONFIG_MISSING_DEFAULT = object()
CONFIG_SAVE_RETRY_COUNT = 5
CONFIG_SAVE_RETRY_DELAY_SEC = 0.03
CONFIG_DEFAULT_NAME = 'default'
CONFIGS_REFRESH_DEBOUNCE_MS = 100


__all__ = [name for name in globals() if name.isupper()]
