MAIN_WINDOW_PAGE_LABEL_FALLBACK = 'Main Window'

THEME_AUTOLOAD_FALLBACK = True
THEME_RUNTIME_RAINBOW_ENABLED_FALLBACK = False
THEME_RUNTIME_RAINBOW_DURATION_FALLBACK = 5000
THEME_RUNTIME_RAINBOW_PALETTE_FALLBACK = 'Pastel'

PATH_SETTING_MODE_FALLBACK = 'directory'
PATH_SETTING_FILE_FILTER_FALLBACK = ''
PATH_SETTING_CAPTION_FALLBACK = 'Select path'

SIDEBAR_EDGE_HIT_WIDTH_FALLBACK = 4
SIDEBAR_EXPAND_THRESHOLD_GAP_MIN_FALLBACK = 12

CONFIG_LOADER_AUTO_SAVE_CONFIG_FALLBACK = False
CONFIG_LOADER_AUTO_SAVE_THEME_FALLBACK = False
CONFIG_LOADER_LOG_DEBUG_FALLBACK = False
CONFIG_LOADER_LOG_INFO_FALLBACK = False
CONFIG_LOADER_LOG_WARNING_FALLBACK = False
CONFIG_LOADER_LOG_ERROR_FALLBACK = False
CONFIG_LOADER_LOG_EXCEPTION_FALLBACK = False
