HTTP_CLIENT_MAX_RETRIES = 5
HTTP_CLIENT_CONNECTIONS_LIMIT = 0
HTTP_CLIENT_TIMEOUT_SECONDS = 5
HTTP_CLIENT_RETRY_DELAY_SECONDS = 2
HTTP_CLIENT_RETRY_BACKOFF = 1.5
HTTP_CLIENT_RETRY_MAX_DELAY_SECONDS = 10


__all__ = [name for name in globals() if name.isupper()]
