WINDOW_X = 900
WINDOW_Y = 500

WINDOW_TITLEBAR_HEIGHT = 32
WINDOW_TITLEBAR_APP_ICON_SIZE = 18
WINDOW_TITLEBAR_BUTTON_WIDTH = 40
WINDOW_TITLEBAR_BUTTON_HEIGHT = 28
WINDOW_TITLEBAR_BUTTON_ICON_SIZE = 14

SIDEBAR_MEDIA_HEIGHT = 96
SIDEBAR_MEDIA_MARGIN = 8

SIDEBAR_MEDIA_GIF_EXTENSIONS = {
    '.gif',
}

SIDEBAR_MEDIA_IMAGE_EXTENSIONS = {
    '.png', '.jpg', '.jpeg', '.bmp',
    '.webp', '.svg', '.ico',
}

SIDEBAR_MEDIA_VIDEO_EXTENSIONS = {
    '.mp4', '.webm', '.avi',
    '.mov', '.mkv',
}

MAIN_WINDOW_PAGE_LABEL_FALLBACK = 'Main Window'
PATH_SETTING_MODE_FALLBACK = 'directory'
PATH_SETTING_FILE_FILTER_FALLBACK = ''
PATH_SETTING_CAPTION_FALLBACK = 'Select path'

SIDEBAR_EDGE_HIT_WIDTH_FALLBACK = 4
SIDEBAR_EXPAND_THRESHOLD_GAP_MIN_FALLBACK = 12


__all__ = [name for name in globals() if name.isupper()]
