CONFIG_COMMENT_SYMBOLS = ('!', '#')
CONFIG_INDENT = ' ' * 2
CONFIG_MISSING_DEFAULT = object()
CONFIG_SAVE_RETRY_COUNT = 5
CONFIG_SAVE_RETRY_DELAY_SEC = 0.03
CONFIGS_REFRESH_DEBOUNCE_MS = 100


__all__ = (
    'CONFIG_COMMENT_SYMBOLS',
    'CONFIG_INDENT',
    'CONFIG_MISSING_DEFAULT',
    'CONFIG_SAVE_RETRY_COUNT',
    'CONFIG_SAVE_RETRY_DELAY_SEC',
    'CONFIGS_REFRESH_DEBOUNCE_MS',
)
