CONFIG_COMMENT_SYMBOLS = ('!', '#')
CONFIG_INDENT = ' ' * 2
CONFIG_MISSING_DEFAULT = object()
CONFIG_SAVE_RETRY_COUNT = 5
CONFIG_SAVE_RETRY_DELAY_SEC = 0.03
CONFIG_DEFAULT_NAME = 'default.txt'
CONFIGS_REFRESH_DEBOUNCE_MS = 100

CONFIG_LOADER_AUTO_SAVE_CONFIG_FALLBACK = False
CONFIG_LOADER_AUTO_SAVE_THEME_FALLBACK = False
CONFIG_LOADER_LOG_DEBUG_FALLBACK = False
CONFIG_LOADER_LOG_INFO_FALLBACK = False
CONFIG_LOADER_LOG_WARNING_FALLBACK = False
CONFIG_LOADER_LOG_ERROR_FALLBACK = False
CONFIG_LOADER_LOG_EXCEPTION_FALLBACK = False


__all__ = (
    'CONFIG_COMMENT_SYMBOLS',
    'CONFIG_INDENT',
    'CONFIG_MISSING_DEFAULT',
    'CONFIG_SAVE_RETRY_COUNT',
    'CONFIG_SAVE_RETRY_DELAY_SEC',
    'CONFIG_DEFAULT_NAME',
    'CONFIGS_REFRESH_DEBOUNCE_MS',
    'CONFIG_LOADER_AUTO_SAVE_CONFIG_FALLBACK',
    'CONFIG_LOADER_AUTO_SAVE_THEME_FALLBACK',
    'CONFIG_LOADER_LOG_DEBUG_FALLBACK',
    'CONFIG_LOADER_LOG_INFO_FALLBACK',
    'CONFIG_LOADER_LOG_WARNING_FALLBACK',
    'CONFIG_LOADER_LOG_ERROR_FALLBACK',
    'CONFIG_LOADER_LOG_EXCEPTION_FALLBACK',
)
