DISCORD_PRESENCE_APP_ID = '1493918950344626216'
DISCORD_PRESENCE_LARGE_IMAGE_KEY = ''
DISCORD_PRESENCE_LARGE_IMAGE_TEXT = 'MeowTool X'
DISCORD_PRESENCE_SMALL_IMAGE_KEY = ''
DISCORD_PRESENCE_SMALL_IMAGE_TEXT = ''


__all__ = [name for name in globals() if name.isupper()]
